#!/usr/bin/env python3
"""
Generates Codex custom-agent role files (TOML) from the Claude Code agent
definitions in plugins/ship/agents/*.md. Stdlib only.

Codex plugins cannot bundle agent roles, so the roles live in
plugins/ship/codex-agents/ship-<agent>.toml and are copied into
~/.codex/agents/ by scripts/install-codex-agents.sh. The .md files stay the
single source of truth: this script prepends codex-agents/_preamble.md (the
Codex tool-name adapter) to each agent body verbatim.

  sync_codex_agents.py                 # (re)write the TOMLs
  sync_codex_agents.py --check         # exit 1 if any TOML differs from what
                                       # would be generated (CI drift check)

ship-git-agent.toml is hand-written and never touched here.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROLES = {
    "spec-agent": {"model": "gpt-5.6-sol", "effort": "xhigh", "sandbox": "read-only"},
    "task-planner-agent": {"model": "gpt-5.6-sol", "effort": "xhigh", "sandbox": "read-only"},
    "implementator-agent": {"model": "gpt-5.6-terra", "effort": "high", "sandbox": "workspace-write"},
    "reviewer-agent": {"model": "gpt-5.6-sol", "effort": "xhigh", "sandbox": "workspace-write"},
    "qa-agent": {"model": "gpt-5.6-terra", "effort": "medium", "sandbox": "workspace-write"},
}

HEADER = (
    "# GENERATED by plugins/ship/scripts/sync_codex_agents.py from plugins/ship/agents/{name}.md.\n"
    "# Do not edit - edit the .md and re-run the script. CI fails on drift.\n"
)

_FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n(.*)\Z", re.DOTALL)


def parse_agent(text):
    """Return (name, one-paragraph description, body) from an agent .md file."""
    match = _FRONTMATTER.match(text)
    if not match:
        raise ValueError("agent file has no YAML frontmatter")
    frontmatter, body = match.group(1), match.group(2).lstrip("\n")
    name_match = re.search(r"^name:\s*(\S+)\s*$", frontmatter, re.M)
    if not name_match:
        raise ValueError("frontmatter has no name:")
    lines = frontmatter.split("\n")
    start = next((i for i, line in enumerate(lines) if line.startswith("description:")), None)
    if start is None:
        raise ValueError("frontmatter has no description:")
    paragraph = []
    for line in lines[start + 1:]:
        if not line.strip():
            break
        paragraph.append(line.strip())
    return name_match.group(1), " ".join(paragraph), body


def render_role(name, description, body, preamble, cfg):
    instructions = f"{preamble.rstrip()}\n\n{body}"
    if not instructions.endswith("\n"):
        instructions += "\n"
    if "'''" in instructions:
        raise ValueError(f"{name}: developer_instructions contains ''' which TOML literal strings cannot hold")
    return (
        HEADER.format(name=name)
        + f'name = "ship-{name}"\n'
        + f"description = {json.dumps(description, ensure_ascii=False)}\n"
        + f'model = "{cfg["model"]}"\n'
        + f'model_reasoning_effort = "{cfg["effort"]}"\n'
        + f'sandbox_mode = "{cfg["sandbox"]}"\n'
        + f"developer_instructions = '''\n{instructions}'''\n"
    )


def generate(plugin_dir):
    plugin_dir = Path(plugin_dir)
    preamble = (plugin_dir / "codex-agents" / "_preamble.md").read_text()
    out = {}
    for agent, cfg in ROLES.items():
        name, description, body = parse_agent((plugin_dir / "agents" / f"{agent}.md").read_text())
        if name != agent:
            raise ValueError(f"{agent}.md declares name {name!r}")
        out[f"ship-{agent}.toml"] = render_role(name, description, body, preamble, cfg)
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="report drift instead of writing")
    parser.add_argument("--plugin-dir", default=str(Path(__file__).resolve().parent.parent))
    args = parser.parse_args(argv)
    plugin_dir = Path(args.plugin_dir)
    try:
        rendered = generate(plugin_dir)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    out_dir = plugin_dir / "codex-agents"
    drift = []
    for filename, text in rendered.items():
        target = out_dir / filename
        current = target.read_text() if target.exists() else None
        if current == text:
            continue
        if args.check:
            drift.append(filename)
        else:
            target.write_text(text)
            print(f"wrote {target}")
    if drift:
        print("codex role files are out of date - run plugins/ship/scripts/sync_codex_agents.py:", file=sys.stderr)
        for filename in drift:
            print(f"  {filename}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
